import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import Form from "../components/Form";
import Result from "../components/Result";
import { useUser } from "@auth0/nextjs-auth0";
import HowTo from "../components/HowTo";

export default function Home() {
  const { user } = useUser();
  // States
  const [url, setUrl] = useState();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [item, setItem] = useState({
    img: "",
    price: "",
    rrp: "",
    title: "",
    saved: false,
  });
  const [show, setShow] = useState(false);

  // Get input from user
  const getUrl = (input_url) => {
    setUrl(input_url);
  };

  // Track item from url
  const trackItem = () => {
    if (!url) {
      setError(true);
    } else {
      setShow(false);
      setError(false);
      setLoading(true);
      axios
        .post("./api/tracker", {
          url: url,
          email: user ? user.email : null,
        })
        .then((res) => {
          setItem({
            img: res.data.img,
            price: res.data.price,
            rrp: res.data.rrp,
            title: res.data.title,
            url: res.data.url,
            saved: res.data.saved,
          });
          setShow(true);
          setLoading(false);
        })
        .catch((err) => {
          setShow(true);
          setLoading(false);
        });
    }
  };

  return (
    <div>
      <Head>
        <title>Amazon Price Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Form
          getUrl={getUrl}
          loading={loading}
          error={error}
          trackItem={trackItem}
        />
        {show && <Result item={item} />}
        <HowTo />
      </div>
    </div>
  );
}
